title: 命运方舟新手攻略
description: 命运方舟攻略，新手职业选择，升级，搬砖，采集，收集，卡牌，符文
theme: just-the-docs

url: https://taogirl.github.io

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/just-the-docs.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: UA-49965095-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)





